version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  redis-service:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
  cache-service:
    image: redis-dist-loc-svc:latest
    container_name: redis-dist-lock-svc
    ports:
      - "8080:8080"
    depends_on:
      - redis-service
    environment:
      REDIS_HOST: redis-service
    restart: always
volumes:
  db:
    driver: local
  cache:
    driver: local