server:
  port: 8080
  servlet:
    context-path: /certtinpay
mongo:
  db:
    ip:
      address:  127.0.01
    port: 27017 
application:
  database: pocdb 
spring:
  application:
    name: certtinpayapi
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name:  org.h2.Driver
    url:  jdbc:h2:mem:payfastaudit_db;DB_CLOSE_DELAY=-1
    username: payfast
    password: payfast
    
# Local Mongodb Config
  data:
    mongodb:
      host: ${mongo.db.ip.address}
      port: ${mongo.db.port}
      database: ${application.database}
      username: cert
      password: cert       